import type { PiAgentKind } from '../../shared/pi-agent-kind'

export function getPiAgentStatusRuntimeDetectionSourceLines(kind: PiAgentKind): string[] {
  if (kind === 'prime-agent') {
    return [
      `const CONFIGURED_HOOK_PATH = '/hook/${kind}'`,
      '',
      'function isOmpRuntime(): boolean {',
      '  return false',
      '}',
      '',
      'function resolveHookPath(_ompRuntime: boolean): string {',
      '  return CONFIGURED_HOOK_PATH',
      '}',
      '',
      'function ompSubagentSessionFile(_ctx: unknown): string | null {',
      '  return null',
      '}',
      '',
      'function describeOmpSubagent(_ctx: unknown, _file: string): Record<string, unknown> {',
      '  return {}',
      '}'
    ]
  }

  return [
    'function processName(value: unknown): string {',
    "  return String(value || '').split(/[\\\\/]/).pop()?.toLowerCase() || ''",
    '}',
    '',
    `const CONFIGURED_HOOK_PATH = '/hook/${kind}'`,
    'let cachedOmpRuntime: boolean | null = null',
    '',
    'function isOmpRuntime(): boolean {',
    '  if (cachedOmpRuntime !== null) return cachedOmpRuntime',
    "  if (CONFIGURED_HOOK_PATH === '/hook/omp') {",
    '    cachedOmpRuntime = true',
    '    return true',
    '  }',
    '  const executableNames = [',
    '    processName(process.title),',
    '    processName(process.env._),',
    '    processName(process.argv[1]),',
    '    processName(process.argv[0])',
    '  ]',
    '  cachedOmpRuntime = executableNames.some((name) =>',
    "    ['omp', 'omp.js', 'omp.sh', 'omp.cmd', 'omp.exe', 'omp.bat'].includes(name)",
    '  )',
    '  return cachedOmpRuntime',
    '}',
    '',
    'function resolveHookPath(ompRuntime: boolean): string {',
    '  // Why: runtime detection keeps a bare-shell OMP launch from reporting as Pi.',
    "  if (ompRuntime) return '/hook/omp'",
    '  return CONFIGURED_HOOK_PATH',
    '}',
    '',
    '// Why: OMP runs subagents in the lead process with their own extension runner, so the',
    '// PID guard cannot tell them apart. Their transcripts live inside the parent session',
    "// directory (OMP's own stats rule), while a lead transcript sits directly in the project dir.",
    'const OMP_SESSION_DIR_PATTERN = /^\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}-\\d{3}Z_[0-9a-f-]{36}$/i',
    '',
    'function ompSubagentSessionFile(ctx: unknown): string | null {',
    '  if (!isOmpRuntime()) return null',
    '  const context = ctx as { hasUI?: unknown; sessionManager?: { getSessionFile?: () => unknown } } | null',
    '  if (!context || context.hasUI === true) return null',
    '  const file = context.sessionManager?.getSessionFile?.()',
    "  if (typeof file !== 'string' || !file) return null",
    '  const segments = file.split(/[\\\\/]/)',
    "  const parentDir = segments.length >= 2 ? segments[segments.length - 2] : ''",
    '  return OMP_SESSION_DIR_PATTERN.test(parentDir) ? file : null',
    '}',
    '',
    'function describeOmpSubagent(ctx: unknown, file: string): Record<string, unknown> {',
    '  const sessionId = (ctx as { sessionManager?: { getSessionId?: () => unknown } }).sessionManager?.getSessionId?.()',
    "  const fileName = file.split(/[\\\\/]/).pop() || ''",
    '  return {',
    "    subagent_id: typeof sessionId === 'string' && sessionId ? sessionId : fileName,",
    "    subagent_label: fileName.replace(/\\.jsonl$/i, ''),",
    '  }',
    '}'
  ]
}
